### ISSUE TITLE
AIML 2.0 Spec implementation?

### ISSUE THREAD

**Issue by stairway-to** [keiffster/program-y#63] opened 2017-07-29 12:03 UTC
Hi,

I'm trying to get [Blackjack.aiml](http://www.square-bear.co.uk/aiml/blackjack.aiml) running.
Some pieces of the code does not work.

```
<category>
<pattern>BLACKJACK</pattern>
<template>
<think>
	<set name="coins">50</set>
	<set name="bankcoin">coins</set>
</think>
Welcome to my Blackjack game. You start the game with <get name="coins"/> coins.<br/><br/>
HOUSE RULES:<br/>
- Dealer must draw to 17<br/>
- Blackjack pays 3 for 2 (rounded up to the nearest coin)<br/>
- Maximum bet is 10 coins<br/>
- The game ends when you either lose all your coins or break the bank by making 250 coins<br/><br/>Good luck!<br/><br/>
Type D to deal.
</template>
</category>

<category>
<pattern>D</pattern>
<that>TYPE D TO DEAL</that>
<template>
<think>
	<set name="topic">BLACKJACK</set>
</think>
Type "QUIT" to end the game.<br/><br/>
Bank: <get name="coins"/> <get name="bankcoin"/>.<br/>
How many coins do you wish to bet (1-10)?
</template>
</category>
```

Removing all the `<br/>` I was able to get the 'BLACKJACK' pattern to work.

For 'that' tag:
I'm not able to get to the 'D' pattern. According to [Pandorabots docs <that>](http://docs.pandorabots.com/aiml/that/), I just need to use the last sentence, 'TYPE D TO DEAL' in this case. Tried doing '* Type D to deal' (with same case & no `<br/>`). Still couldn't get it to work.

**BLACKJACK**
_Welcome to my Blackjack game. You start the game with 50 coins. HOUSE RULES: - Dealer must draw to 17 - Blackjack pays 3 for 2 (rounded up to the nearest coin) - Maximum bet is 10 coins - The game ends when you either lose all your coins or break the bank by making 250 coins Good luck! Type D to deal._
**D**
_Sorry, I don't have an answer for that!_
 

But for some reason the following works. I'm not able to figure out what's the difference.
```
   <category>
      <pattern>HI</pattern>
      <template>Do you like comedy movies</template>  
   </category>
   
   <category>
      <pattern>YES</pattern>
      <that>* comedy movies</that>
      <template>Nice, I like comedy movies too.</template>
   </category>
   
   <category>
      <pattern>NO</pattern>
      <that>* comedy movies</that>
      <template>Ok! But I like comedy movies.</template>
   </category> 
```
**HI**
_Do you like comedy movies_
**NO**
Ok! But I like comedy movies.

I have to port ~30 aiml files.
 
 - How can I change the aiml to get this working? Any way to know what tags work and what doesn't?
 - How can I get to work on extending the required behaviour using program-y?

Thanks!

**Comment by keiffster** [comment] 2017-07-30 16:16
Looks like an issue with multi sentence responses not getting parsed correctly into the that tag

Give me a couple of days and I'll get you a fix

**Comment by keiffster** [comment] 2017-07-31 07:14
As I thought, a problem in the that parser which failed to identify the last sentence correctly. This has now been fixed on master and I've just pushed the latest code and tests.

I've also included blackjack.aiml into the Alice2 bot and had fun playing the game this morning

K

**Comment by stairway-to** [comment] 2017-07-31 10:10
Awesome! I'll check it out.

**Comment by stairway-to** [comment] 2017-07-31 15:38
Just realized, `<br/>` tag doesn't work yet. Is this not supported? I saw the script in alice2/blackjack.aiml which contains, `<br/>`. I'm not sure why this is not working for me.

**Comment by keiffster** [comment] 2017-07-31 18:48
Can you provide some context. When you say it's not working how is it not working

Can you provide an example ?

K

Keith Sterling
E: keith@keithsterling.com
M: +44 (0) 7771 597 630

**Comment by stairway-to** [comment] 2017-07-31 21:08
```
<category>
    <pattern>TEST</pattern>
    <template>
    	Line 1
  	Line 2
    </template>
</category>
```

output:
**Hi, how can I help you today?**
_>>> test_
**Line 1 Line 2**

```
<category>
    <pattern>TEST</pattern>
    <template>
    	Line 1
        <br/>
  	Line 2
    </template>
</category>
```

output:
**Hi, how can I help you today?**
_>>> test_
**Sorry, I don't have an answer for that!**

**Comment by keiffster** [comment] 2017-07-31 21:41
Ok looks like the fix for blackjack has caused a regression in the html parser. Should be a quick fix in the morning

**Comment by keiffster** [comment] 2017-08-01 06:45
So I just tried the following grammar in both Alice2 and Y-Bot 

```
<?xml version="1.0" encoding="UTF-8"?>
<aiml version="2.0">

    <category>
		<pattern>TEST1</pattern>
		<template>
			Line1
			Line2
		</template>
	</category>

	<category>
		<pattern>TEST2</pattern>
		<template>
			Line1
			<br/>
			Line2
		</template>
	</category>

</aiml>
```

And the results worked, returning either
```
Line1 Line2
```
And 
```
Line1
 Line2
```
Can you tell me which bot you were running this grammar under ?

**Comment by stairway-to** [comment] 2017-08-01 11:37
I'm running this under Alice2.

```
Loading, please wait...
No bot root argument set, defaulting to [.]
ALICE 2.0 version 0.0.5, initiated October 9, 2012
Hi, how can I help you today?
>>> test1
Line1 Line2
>>> test2
Sorry, I don't have an answer for that!
>>> 
```

**Comment by keiffster** [comment] 2017-08-01 11:53
Certainly strange, I did a test this morning against Alice2 and it worked fine

```
Loading, please wait...
No bot root argument set, defaulting to [.]
ALICE 2.0 version 0.0.5, initiated October 9, 2012
Hi, how can I help you today?
>>> test1
Line1 Line2
>>> test2
Line1
Line2
>>> 
```

Are you Linux, Mac or Windows ?

Also have you had a look at the log file , is there an error or exception being displayed ?

**Comment by stairway-to** [comment] 2017-08-01 12:36
I'm on Mac.

I'm getting the error on all .aiml files:
`No node [xml] registered in Template Node Factory in [./aiml/blackjack.aiml]`

In my config folder, I have `preprocessors.conf` `template_nodes.conf` `test_postprocessors.conf` `postprocessors.conf` `pattern_nodes.conf` & `*.txt`

**Comment by keiffster** [comment] 2017-08-01 12:43
Ok, I know exactly what the problem is then, I caused this when I refactored the config files to support Windows, and copied the settings for pattern and template nodes into each config file without the associated config files

I've just added them and run Alice 2 which is working

Fix just pushed to master

**Comment by stairway-to** [comment] 2017-08-01 13:59
Still getting the same error.

Pulled latest commit("Added node config files to all bots") -> ran y-bot:
```
Hi, how can I help you today?
>>> test1
Line1 Line2
>>> test2
Sorry, I don't have an answer for that! 
```

In /tmp/y-bot_errors.txt
```
No node [xml] registered in Template Node Factory in [./aiml/scratch.aiml]
No node [xml] registered in Template Node Factory in [./aiml/core/aimlstandardlibrary.aiml]
No node [xml] registered in Template Node Factory in [./aiml/core/bot_profile.aiml]
No node [xml] registered in Template Node Factory in [./aiml/core/bot_profile.aiml]
.
.
.
```

**Comment by keiffster** [comment] 2017-08-17 19:47
Are you still having a problem with this ?

Its been reported before and is usually when people have created their own bots, but when I refactored all of the config files, people are still using the old files.

Let me know and if you still having a problem I can talk you through upgrading your config

K

**Closed** 2017-08-21 12:50 UTC
