### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by macasas** [keiffster/program-y#190] opened 2019-02-24 21:25 UTC
Does this repo actually install and work?

I have spent a few hours reading your wiki and like the idea. I installed it, but then found every sh script file refers to paths that do not exist, src/programy/client/console.py for example, config.yaml files that are not there, "Once you have your access token, you need to add an entry into the license.kets file", where is that? etc. etc.  Did you reorganise your folder structure for v3 but without updating the wiki or tutorials? or am I just too stupid to get this working?

**Comment by keiffster** [comment] 2019-02-24 21:34
Have you followed the install instructions at

https://github.com/keiffster/program-y/wiki/Install

Which way did you install ? Via pip or got clone

Which is are you using

Did you run the admin tool as per the instructions above

Which bot did you decide to install

Which .sh script are you trying to run

Then path you include to console.py exists but sounds like you have a path issue

**Comment by macasas** [comment] 2019-02-24 21:45
I cloned the git repo to take a look at the files.
Then I created a pyenv virtualenv and installed programy using pip

I am on OSX Mojave 10.14.3

I just ran python3 -m programy.admin.tool install template-y
and i get Missing additional component from install command ['textblob']
Available commands are:
	help
	list
	download <bot-name>
	install <component>

The console.py is a folder down in /events, not in src/programy/clients

It's quite possible I have a path error, but I think I have followed your instructions and here I am floundering.  I have been having issues with python 3.7 but I see you are using that in your virtual environment, I will start again, as I get the feeling from your response that the answer to my question is an emphatic "yes", so at least I feel I am not wasting my time trying to get this working.  Thanks for your quick response.

**Comment by keiffster** [comment] 2019-02-24 21:51
Maybe a proble with template-y which just needs a doc update

In terms of install you need to first ‘install’ textblob

Then you ‘download’ template-y

From you comments it sounds like you tried to install template-y

Follow the instructions for y-bot s per the wiki and tell me how you get on, that will get you a full bot running and give me time to check out template-y docs

Ps I use OS X for all my dev so usually tested first

**Comment by keiffster** [comment] 2019-02-24 21:57
I see what the issue is, I’ve not updated the Python paths in the clients pages since the files where moved

These will all be updated first thing in the morning !!!

**Comment by macasas** [comment] 2019-02-24 21:59
Okay, I have followed the link.
added 3.7.2 to my versions in pyenv
I missed the textblob command last time around
this time I downloaded y-bot and I have a full folder structure
Because I didn't get this before, I think I will looking in the programy folder structure for files, rather than the generated bot project structure, which now makes more sense now I can see it.

Thanks very much for you help.

**Comment by keiffster** [comment] 2019-02-24 22:02
Glad to be of help getting you up and running

But also thanks for spotting an issue with the docs that needs fixing

K

**Comment by macasas** [comment] 2019-02-24 22:48
Just a quick update. Installed y-bot, added a license.keys file as per the readme and ran y-bot.sh without issue, but when I run y-bot-telegram.sh it works, but sends the cpu running at 100+% for python 3.7. Is there a setting that could drop this down, turn off debug or something because this seems excessive amount of cpu.

**Comment by keiffster** [comment] 2019-02-25 07:56
I see that Telegram Python library 11.1.0 has an additional method to put the updater into idle mode. This is a one line change which I added this morning and will push the changes to master within the next 24 hours or so.

This brought CPU usage back to minimal

**Comment by macasas** [comment] 2019-02-25 08:50
Look forward to that.

storage/lookups/person.txt is full of the 2 character, this came out in the conversation and I cannot think of any reason why it should be there.

If I clone the repo, where are the source files, like person.txt that generate the bots, cannot find them anywhere to edit and push back to you?

**Comment by keiffster** [comment] 2019-02-25 13:12
Not sure what you mean, I've just had a look at person.txt in Y-Bot

https://github.com/keiffster/y-bot/blob/master/storage/lookups/person.txt

And it does not have the 2 character

**Comment by macasas** [comment] 2019-02-25 13:14
with me2
with you2



On 25 February 2019 at 13:12:04, Keith Sterling (notifications@github.com)
wrote:

Not sure what you mean, I've just had a look at person.txt in Y-Bot

https://github.com/keiffster/y-bot/blob/master/storage/lookups/person.txt

And it does not have the 2 character

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keiffster/program-y/issues/190#issuecomment-467005675>,
or mute the thread

**Comment by keiffster** [comment] 2019-02-25 13:32
Ok, see what you mean, this is part of the original AIML Specification and is meant to be there

The `<person>` and `<person2>` tags are not that useful and are rarely used these days, but for backward compatibility with PandoraBots, Alice and Rosie they are kept in

**Comment by macasas** [comment] 2019-02-25 13:35
I only noticed it because the 2 came out in the conversation and obviously
looks like a typo, which it is.


On 25 February 2019 at 13:32:15, Keith Sterling (notifications@github.com)
wrote:

Ok, see what you mean, this is part of the original AIML Specification and
is meant to be there

The <person> and <person2> tags are not that useful and are rarely used
these days, but for backward compatibility with PandoraBots, Alice and
Rosie they are kept in

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keiffster/program-y/issues/190#issuecomment-467012016>,
or mute the thread

**Comment by keiffster** [comment] 2019-02-26 20:38
Telegram client has now been updated and released in v3.6.2

**Closed by keiffster** 2019-02-26 20:38 UTC

**Comment by impulsecorp** [comment] 2019-11-01 14:27
FYI, for anybody else having this problem, like in this example:
Question:  Did you eat food
Answer: "No I didn't did me2 eat food. What's did me2 eat food like?"

To fix it I edited https://github.com/keiffster/y-bot/blob/master/storage/lookups/person.txt
to delete the top part it which converts words to "me2" (and similar "2" words).  

In my example above, it now keeps the word "you" instead of converting it to "me2":
"No I didn't did you eat food. What's did you eat food like?"
